/**:
  ros__parameters:
    model_params:
      model_params_version: "1.0.0"
      class_names: ["CAR", "TRUCK", "BUS", "BICYCLE", "PEDESTRIAN"]
      point_feature_size: 4
      max_voxel_size: 40000
      point_cloud_range: [-76.8, -76.8, -4.0, 76.8, 76.8, 6.0]
      voxel_size: [0.32, 0.32, 10.0]
      downsample_factor: 1
      encoder_in_feature_size: 9
      has_variance: false
      has_twist: false
      # Distances in bev meters
      # 0-50m, 50.0-90m, 90.0-121.0m, 121.0-inf
      score_distances: [
        50.0,
        90.0,
        121.0
      ]
      # CAR, TRUCK, BUS, BICYCLE, PEDESTRIAN
      score_thresholds:
        [
          # Must match with score_distances
          # 0-50m, 50.0-90m, 90.0-121.0m, 121.0-inf
          # CAR
          [0.35, 0.35, 0.35, 0.35],
          # TRUCK
          [0.35, 0.35, 0.35, 0.35],
          # BUS
          [0.35, 0.35, 0.35, 0.35],
          # BICYCLE
          [0.35, 0.35, 0.35, 0.35],
          # PEDESTRIAN
          [0.35, 0.35, 0.35, 0.35],
        ]
