/**:
  ros__parameters:
    dynamic_avoidance:
      common:
        enable_debug_info: false
        use_hatched_road_markings: true

      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: false
        bicycle: true
        motorcycle: true
        pedestrian: true

        successive_num_to_entry_dynamic_avoidance_condition: 5
        successive_num_to_exit_dynamic_avoidance_condition: 1

        min_obj_lat_offset_to_ego_path: 0.0 # [m]
        max_obj_lat_offset_to_ego_path: 1.0 # [m]

        front_object:
          min_object_vel: -0.5               # [m/s] The value is negative considering the noisy velocity of the stopped vehicle.
          max_ego_path_lat_cover_ratio: 0.3  # [-] The object will be ignored if the ratio of the object covering the ego's path is higher than this value.

        stopped_object:
          max_object_vel: 0.5 # [m/s] The object will be determined as stopped if the velocity is smaller than this value.

      drivable_area_generation:
        lat_offset_from_obstacle: 1.0 # [m]
        margin_distance_around_pedestrian: 2.0 # [m]
        max_lat_offset_to_avoid: 0.5 # [m]
        max_time_for_object_lat_shift: 0.0 # [s]
        lpf_gain_for_lat_avoid_to_offset: 0.9 # [-]
