/**:
  ros__parameters:
    onnx_path: "$(var model_path)/frnet_$(var sensor_model).onnx"
    trt_precision: fp16
    filter:
      class_confidence_threshold: 0.05
      classes: ["drivable_surface"]
      ego_crop_box:
        reference_frame: base_link
        min_x: -1.53
        min_y: -1.15
        min_z: -0.1
        max_x: 5.9
        max_y: 1.15
        max_z: 3.1
