/**:
  ros__parameters:
    model_params:
      trt_precision: "fp16"
      use_temporal: true                                        # Can the model use temporal information or not.
    post_process_params: # These are post-processing parameters to improve the predictions.
      confidence_threshold: [0.36, 0.39, 0.38, 0.41, 0.43]  # Per-class thresholds: [CAR, TRUCK, BUS, BICYCLE, PEDESTRIAN]
      circle_nms_dist_threshold: 0.0   # turn off circle NMS by setting 0.0, otherwise set to around 0.5
      iou_nms_search_distance_2d: 10.0
      iou_nms_threshold: 0.5           # set to 0 to turn off iou NMS
      yaw_norm_thresholds: [0.3, 0.3, 0.3, 0.3, 0.0]
