/**:
  ros__parameters:
    filter_names:
      [
        "autoware::trajectory_safety_filter::plugin::OutOfLaneFilter",
        "autoware::trajectory_safety_filter::plugin::CollisionFilter",
        "autoware::trajectory_safety_filter::plugin::VehicleConstraintFilter",
      ]
    # available filters:
    #  "autoware::trajectory_safety_filter::plugin::OutOfLaneFilter"
    #  "autoware::trajectory_safety_filter::plugin::CollisionFilter"
    #  "autoware::trajectory_safety_filter::plugin::VehicleConstraintFilter"

    out_of_lane:
      time: 2.0
      min_value: 0.0

    collision:
      time: 3.0
      min_value: 2.0

    vehicle_constraint:
      max_velocity: 10.0 # m/s
      max_acceleration: 2.0 # m/s^2
      max_deceleration: 2.0 # m/s^2 (positive value, but represents deceleration)
      max_steering_angle: 0.5 # rad
      max_steering_angle_rate: 0.1 # rad/s
