/**:
  ros__parameters:
    filter_names: ["autoware::trajectory_traffic_rule_filter::plugin::TrafficLightFilter"]
    traffic_light_filter:
      max_accel: -2.8
      max_jerk: -5.0
      delay_response_time: 0.5
      yellow_lamp_period: 2.75
      yellow_light_stop_velocity: 1.0 # Velocity threshold (m/s) below which the vehicle will always stop before the traffic light when the signal turns yellow, regardless of the pass_judge decision.
      enable_pass_judge: true
